import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Transactions from './transactions'
import Currencies from './currencies'
import TradeSessions from './tradesessions'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto Auto Trader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Welcome to Cryptobot 5000!
          </h1>

          <p className={styles.description}>
            Get started by clicking Start Trading!
          </p>
        </div>

        <div className={styles.buttoncontainer}>
            <button onClick={startTrading}> start trading! </button>
            <button onClick={stopTrading}> stop trading! </button>
          </div>

        <div className={styles.bodycontainer}>
          <Currencies></Currencies>
          <Transactions></Transactions>
          <TradeSessions></TradeSessions>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

function startTrading(e) {
  console.log("start clicked" + e)
  fetch('https://cryptoautotrader-production.up.railway.app/v1/trade-sessions/start', {
    method: 'POST',
    headers: {
      'x-user-id': 'd78964af-9dbe-4613-bf46-f3701bdd0494'
    }
  }) 
    .then((response) => response.json())
    .then((data) => console.log(data))
}

function stopTrading() {
  console.log("stop clicked")
  fetch('https://cryptoautotrader-production.up.railway.app/v1/trade-sessions/stop/a91aa853-8301-4db2-a38e-b3bdc56056f3', {
    method: 'POST',
    headers: {
      'x-user-id': 'd78964af-9dbe-4613-bf46-f3701bdd0494'
    }
  }) 
    .then((response) => response.json())
    .then((data) => console.log(data))
}