import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Transactions from './transactions'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Cryptobot 5000!
        </h1>

        <p className={styles.description}>
          Get started by clicking Start Trading!
        </p>

        <div className={styles.button}>
          <button onClick={handleClick}> start trading! </button>
          <button onClick={handleClick}> stop trading! </button>
        </div>
        <Transactions></Transactions>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

function handleClick() {
  console.log("clicked")
}