import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Transactions from '../../components/transactions'
import Currencies from '../../components/currencies'
import TradeSessions from '../../components/tradesessions'
import { useGlobalContext } from '../../contexts';



export default function Home() {
  const { 
    userID, setUserID, 
    tradeSessionID, setTradeSessionID
   } = useGlobalContext();
  console.log('dashboard: current user id ' + userID)

  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto Auto Trader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div>
            <h1 className={styles.title}>
              Welcome to Cryptobot 5000!
            </h1>
          </div>
      </header>

      <main className={styles.main}>
        <div className={styles.buttoncontainer}>
          <button onClick={() => { startTrading(userID, setTradeSessionID) }}> start trading! </button>
          <button onClick={() => { stopTrading(userID, tradeSessionID) }}> stop trading! </button>
        </div>

        <div className={styles.bodycontainer}>
          <Currencies></Currencies>
          <Transactions></Transactions>
          <TradeSessions></TradeSessions>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

function startTrading(userID, setTradeSessionIDFunc) {
  console.log("start clicked " + userID)
  fetch('https://cryptoautotrader-production.up.railway.app/v1/trade-sessions/start', {
    method: 'POST',
    headers: {
      'x-user-id': userID
    }
  }) 
    .then((response) => response.json())
    .then((data) => {
      console.log(data)
      setTradeSessionIDFunc(data.trade_id)
    })
}

function stopTrading(userID, tradeSessionID) {
  console.log("stop clicked " + userID)
  fetch('https://cryptoautotrader-production.up.railway.app/v1/trade-sessions/stop/' + tradeSessionID, {
    method: 'POST',
    headers: {
      'x-user-id': userID
    }
  }) 
    .then((response) => response.json())
    .then((data) => console.log(data))
}